apiVersion: apps/v1
kind: Deployment
metadata:
  name: gagan-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-gagan
  template:
    metadata:
      labels:
        app: my-gagan
    spec:
      containers:
      - name: my-image
        image: gagandeepthinknyx/intel1:latest
        ports:
        - containerPort: 8080
